fragment DocsOverviewParts on DocsOverview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsFoundationsParts on DocsFoundations {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsOverviewParts on DocsComponentsOverview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsActionsParts on DocsComponentsActions {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsInputsParts on DocsComponentsInputs {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsNavigationParts on DocsComponentsNavigation {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsFeedbackParts on DocsComponentsFeedback {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsComponentsDisplayParts on DocsComponentsDisplay {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsPatternsParts on DocsPatterns {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment DocsResourcesParts on DocsResources {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}
