fragment Docsos4OverviewParts on Docsos4Overview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4FoundationsParts on Docsos4Foundations {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsOverviewParts on Docsos4ComponentsOverview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsActionsParts on Docsos4ComponentsActions {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsInputsParts on Docsos4ComponentsInputs {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsNavigationParts on Docsos4ComponentsNavigation {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsFeedbackParts on Docsos4ComponentsFeedback {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsDisplayParts on Docsos4ComponentsDisplay {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4PatternsParts on Docsos4Patterns {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ResourcesParts on Docsos4Resources {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5OverviewParts on Docsos5Overview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5FoundationsParts on Docsos5Foundations {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsOverviewParts on Docsos5ComponentsOverview {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsActionsParts on Docsos5ComponentsActions {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsInputsParts on Docsos5ComponentsInputs {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsNavigationParts on Docsos5ComponentsNavigation {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsFeedbackParts on Docsos5ComponentsFeedback {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsDisplayParts on Docsos5ComponentsDisplay {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5PatternsParts on Docsos5Patterns {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ResourcesParts on Docsos5Resources {
  __typename
  title
  description
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}
