fragment Docsos4OverviewParts on Docsos4Overview {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4IconsParts on Docsos4Icons {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4GeneralParts on Docsos4General {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsOverviewParts on Docsos4ComponentsOverview {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsNavigationParts on Docsos4ComponentsNavigation {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsActionsParts on Docsos4ComponentsActions {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsInputsParts on Docsos4ComponentsInputs {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsContainersParts on Docsos4ComponentsContainers {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4ComponentsDisplayParts on Docsos4ComponentsDisplay {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4InteractionParts on Docsos4Interaction {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4SystemParts on Docsos4System {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4MultiDeviceParts on Docsos4MultiDevice {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos4BestPracticesParts on Docsos4BestPractices {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5OverviewParts on Docsos5Overview {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5IconsParts on Docsos5Icons {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5GeneralParts on Docsos5General {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsOverviewParts on Docsos5ComponentsOverview {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsNavigationParts on Docsos5ComponentsNavigation {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsActionsParts on Docsos5ComponentsActions {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsInputsParts on Docsos5ComponentsInputs {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsContainersParts on Docsos5ComponentsContainers {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5ComponentsDisplayParts on Docsos5ComponentsDisplay {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5InteractionParts on Docsos5Interaction {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5SystemParts on Docsos5System {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5MultiDeviceParts on Docsos5MultiDevice {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}

fragment Docsos5BestPracticesParts on Docsos5BestPractices {
  __typename
  title
  description
  maintainer
  maintainerOpenId
  status
  platforms
  figmaFileKey
  figmaNodeId
  figmaPrototypeUrl
  tokenGroups
  body
}
